### ISSUE TITLE
Participants block content

### ISSUE THREAD

**Issue by tyohan** [w3id/webunconfid-website#1]
@satyakresna @ri7nz ada yang bisa bantuin bikin pakai web component untuk profile peserta yang bakal hadir? Datanya ada di Google Drive nanti saya bisa invite. Layoutnya dibikin mirip kayak organizers, ada di `src/t-participants.js` tapi dengan struktur:

Foto
Nama
Komunitas
Topik yang disukai

**Comment by ri7nz** [comment]
Baik, dengan senang hati @tyohan

**Comment by tyohan** [comment]
Di Google Drive yang di share itu ada 2
Google Sheet data peserta -> ubah ke JSON nanti data JSON itu akan kita jadikan acuan update daftar partisipan.
Photo peserta -> save ke 1 folder dan rename dengan format full_name.jpg

**Comment by satyakresna** [comment]
Maaf baru balas mas, saya ikut bantuin @ri7nz  sambil belajar Web Components lagi, sudah lama ngga pegang. Barusan kita diskusi cara fetch json dari web componentsnya lit-html.

**Comment by satyakresna** [comment]
Btw si @ri7nz sudah dapat akses google drive nya ngga? Kalau sudah, boleh saya dikasih akses juga mas @tyohan ? Nanti bingung saya gimana nyoba kalau belum ada datanya. He he he.

**Comment by ri7nz** [comment]
@tyohan  @satyakresna  tolong di review yah https://github.com/w3id/webunconfid-website/pull/2

**Comment by satyakresna** [comment]
Kemarin saya ngasih referensi cara fetch json ke @ri7nz dengan lit-html pakai until sesuai artikel ini: https://alligator.io/web-components/lit-html/

**Comment by ri7nz** [comment]
@satyakresna  pada artikel berbeda path dengan package / dependencies yang di install sebelumnya oleh mas @tyohan . 

di artikel seperti ini 
```
import { repeat } from './node_modules/lit-html/lib/repeat.js';
import { until } from './node_modules/lit-html/lib/until.js';
```
setelah saya check kembali, seperti ini 
```
import { repeat } from '../node_modules/lit-html/directives/repeat.js';
import { until } from '../node_modules/lit-html/directives/until.js';
```

mungkin versionnya berbeda dengan dependencies yang exist pada project kita (https://github.com/w3id/webunconfid-website)

thanks banget yah @satyakresna

**Comment by satyakresna** [comment]
Iya bro, itu artikel tahun lalu. Kalau ngga salah itu lit-html versi 0.9 yg
dipakai di artikel itu. Sekarang si until pindah ke folder directives. Sip,
sama".

**Comment by satyakresna** [comment]
Ini kelihatannya juga sudah beres mas @tyohan .
