### ISSUE TITLE
Minor UI bug

### ISSUE THREAD

**Issue by filosofikode** [w3id/webunconfid-website#15]
Ketika click `a#arrow-down`, malah toggle class `active` ke `div#drawer` 

Tidak terlalu critical, tapi sedikit menganggu

https://imgur.com/a/7IVJwnf

**Comment by nusendra** [comment]
wah baru mau bikin issue ini haha. ternyata udah di tanyain duluan. ntap mas fariz

**Comment by ri7nz** [comment]
![localhost_5000_](https://user-images.githubusercontent.com/16365952/45523606-68071d00-b7f4-11e8-8d7e-f9baa775c59e.png)

@filosofikode  sudah di perbaiki oleh mas @tyohan  https://github.com/w3id/webunconfid-website/commit/17076a8591e0ab78a4cb1ae8456ad1b519b094e2 
mungkin belum di deploy pada web resminya

**Comment by filosofikode** [comment]
Nice. Keep the good work!

**Comment by ri7nz** [comment]
Thank you so much @filosofikode , Keep the good work too !
