### ISSUE TITLE
Fix scroll to behavior & horizontal center of arrow down

### ISSUE THREAD

**Issue by wahyubucil** [w3id/webunconfid-website#25]
Behavior scroll to yang menggunakan block center terlihat tidak bagus. Apalagi ketika di mobile

Contohnya ketika klik menu Organizer, itu akan membawa scroll ke tengah konten organizer, jadi terlihat kurang bagus.
<img width="381" alt="screen shot 2018-09-14 at 9 45 04 pm" src="https://user-images.githubusercontent.com/30768993/45553882-a12ca500-b867-11e8-97b2-ef4319f284ad.png">

Lebih baik, dibawa ke atas atau diawal konten mulai (start), tepatnya diatas judul setiap konten.

Dan pada arrow down. Element tersebut kurang pas ketengah.

**Comment by eezhal92** [comment]
apakah issue ini sudah solved dgn PR ini #26 ?

**Comment by wahyubucil** [comment]
Sudah solved. Saya close ya issue ini. Terimakasih.
