### ISSUE TITLE
NPM install failed

### ISSUE THREAD

**Issue by ivankristianto** [w3id/webunconfid-website#28]
Saya berusaha `npm install` tapi failed karena ada package yang kosong:
https://github.com/w3id/webunconfid-website/blob/master/package.json#L25

paket apakah itu?

cc: @tyohan

**Comment by ri7nz** [comment]
@ivankristianto  sudah di perbaiki mas. boleh di periksa ulang lagi @ivankristianto ( Good Job )

**Comment by eezhal92** [comment]
Mungkin issuenya bisa di close

**Comment by ivankristianto** [comment]
Yup, sudah okay sekarang. thanks ya.
