### ISSUE TITLE
Add webpack for development mode

### ISSUE THREAD

**Issue by mazipan** [w3id/webunconfid-website#3]
Now, webpack only serve production mode.
Need to setup for development env.

Also please add shortcut in package.json then I can run with just `yarn run dev`

**Comment by tyohan** [comment]
@mazipan itu masih konflik dengan yang @satyakresna. Kalau udah fix harusnya sisa di merge.

**Comment by satyakresna** [comment]
Di tempat saya sudah beres mas @tyohan . Silahkan di merge pull request nya #14 .
