### ISSUE TITLE
Error overlay unable to locate 'participants.json' 

### ISSUE THREAD

**Issue by eezhal92** [w3id/webunconfid-website#35]
Barusan fetch latest, branch master. Pas run `yarn dev`, muncul error ini:

![image](https://user-images.githubusercontent.com/7058456/45586917-62125880-b928-11e8-931e-db6f3d3b54b3.png)

**Comment by ri7nz** [comment]
solve on this pr https://github.com/w3id/webunconfid-website/pull/31
