### ISSUE TITLE
Membedakan folder ouput webpack

### ISSUE THREAD

**Issue by eezhal92** [w3id/webunconfid-website#37]
https://github.com/w3id/webunconfid-website/blob/master/webpack.config.common.js#L8

Mungkin agar lebih clear, output bundling mungkin bisa di taruh di directory `dist`.
```javascript
module.exports = {
  ...
  output: {
-   filename: 'src/t-app.js',
+   filename: 'dist/t-app.js',
    path: path.resolve(__dirname, 'dist')
  },
  ...
}
```

```html
<script type="module" src="dist/t-app.js" async></script>

```

**Comment by tyohan** [comment]
Itu output webpack udah semua file dimasukkan di `dist` kalau nama di atas diganti ada 2 hal
* jadi redundant karena bakal jadi dist/dist/t-app.js
* harus pakai plugin html webpack untuk bikin template index.html

Jadi saat ini mungkin bukan prioritas.

**Comment by eezhal92** [comment]
Ah i see 👌
