### ISSUE TITLE
Milligram css pointing to node_modules

### ISSUE THREAD

**Issue by mazipan** [w3id/webunconfid-website#4]
Fix path that pointing to node_modules

**Comment by mazipan** [comment]
Is we really need Milligram @ri7nz ?
Can we remove that?

**Comment by eezhal92** [comment]
Mungkin ada kaitannya dengan ini #13

**Comment by ri7nz** [comment]
@mazipan  maybe, we can wait for the response from @tyohan for milligram css.

**Comment by tyohan** [comment]
@mazipan @ri7nz any suggestion for typography only CSS framework? Baseline grid typography make text content looks better.
