### ISSUE TITLE
Add web component loader to support unsupported browsers

### ISSUE THREAD

**Issue by tyohan** [w3id/webunconfid-website#44]
Put issue to track what I'm working on

**Comment by achmadk** [comment]
workaround in firefox (latest version);

1. Open new tab then type `about:config` in firefox's address bar.
2. search `webcomponent` in its searchbar.
3. set `dom.webcomponents.customelements.enabled` and `dom.webcomponents.shadowdom.enabled` value to `true`.

**Comment by tyohan** [comment]
added
