### ISSUE TITLE
Ada issue lain yang bisa dibantu?

### ISSUE THREAD

**Issue by eezhal92** [w3id/webunconfid-website#5]
Halo mas @tyohan. Apakah ada issue lain yang bisa dibantu?

Dengan senang hati saya bisa ikut kontribusi :)

**Comment by ri7nz** [comment]
@eezhal92  coba dilihat ini bro 
https://github.com/w3id/webunconfid-website/issues/4
https://github.com/w3id/webunconfid-website/issues/3
