### ISSUE TITLE
Autodeploy?

### ISSUE THREAD

**Issue by ivankristianto** [w3id/webunconfid-website#52]
Baru nyadar kalau kita belum punya autdeploy jika PR di merge ke master?
Siapa ya yang pegang deployment ke production?
cc @tyohan @ri7nz

**Comment by ri7nz** [comment]
mas @tyohan yang pegang mas

Pada tanggal Sel, 18 Sep 2018 pukul 13.25 Ivan Kristianto <
notifications@github.com> menulis:

**Comment by tyohan** [comment]
Ini di host di Firebase. Nanti kita bisa set untuk autodeploy via Travis. Nanti saya coba set minggu ini ya.

**Comment by tyohan** [comment]
Travis added tapi masih belum ke deploy. Masih exit build 0 di yarn build.

**Comment by ivankristianto** [comment]
Saya lihat di karenakan ada 3 files yang yang ukurannya > 244Kb.
saya rasa perlu di compress atau reduce file size nya

**Comment by tyohan** [comment]
Now it will auto deploy whenever we push the code to server. So make sure everyone pull request to dev only not to server.
