### ISSUE TITLE
BUG: Browser Compatibility 

### ISSUE THREAD

**Issue by ri7nz** [w3id/webunconfid-website#54]
![image](https://user-images.githubusercontent.com/16365952/45676387-cf59ff80-bb5b-11e8-95c6-3b9962106193.png)

Live Website WebUnconfID its not working on Firefox (Teste by Me) 

firefox version : 61.0.1 (64-bit) (Linux | Ubuntu)

**Comment by tyohan** [comment]
@ri7nz Firefox need to flag web component on Firefox. related with #44 
Check https://caniuse.com/#feat=custom-elementsv1

**Comment by ri7nz** [comment]
@tyohan  thank you so much. This is the issue can be closed
