### ISSUE TITLE
Lazy load on image

### ISSUE THREAD

**Issue by tyohan** [w3id/webunconfid-website#58]
Kayaknya `t-img` bisa dibikin lazy load dari component pake intersection observer. Yang perlu diperhatikan `t-img` ga pakai tag `img` jadi image di-load via` background-image`.

Jangan lupa pastikan add polyfil kalau ke-detect browser ga support natively intersection observer

**Comment by eezhal92** [comment]
Belum pernah implement lazyload. Tapi saya minat garap issue ini mas @tyohan
