### ISSUE TITLE
Auto fetch and save as json for schedule

### ISSUE THREAD

**Issue by tyohan** [w3id/webunconfid-website#59]
Kita sudah bisa akses json feed untuk schedule via link ini 

https://ical-to-json.herokuapp.com/convert.json?url=https%3A%2F%2Fcalendar.google.com%2Fcalendar%2Fical%2Fqu110c8pvuem82r9o0d6tln5d4%2540group.calendar.google.com%2Fpublic%2Fbasic.ics

Tapi pengennya mending json itu di download langsung ke `data/schedule.json` kalau kita jalanin `yarn dev` atau `yarn build`.

Anyone can work on this?

**Comment by ri7nz** [comment]
@tyohan forbidden linknya Kak
![selection_414](https://user-images.githubusercontent.com/16365952/45769503-04ed0e80-bc6a-11e8-9482-e320b7fdfc29.png)

**Comment by tyohan** [comment]
Kayaknya dia ga bisa direct call dan harus dipanggil dulu via [halaman ini](https://ical-to-json.herokuapp.com/convert?url=https%3A%2F%2Fcalendar.google.com%2Fcalendar%2Fical%2Fqu110c8pvuem82r9o0d6tln5d4%2540group.calendar.google.com%2Fpublic%2Fbasic.ics).

**Comment by tyohan** [comment]
Untuk sekarang ga usah berarti. Manual import dulu saja @ri7nz. Saya close dulu.

**Comment by ri7nz** [comment]
file .json nya mengikuti link diatas saja langsung dan di save ke folder data ? @tyohan
