### ISSUE TITLE
Lebih cantik pakai logo komunitas di section komunitas? 😁

### ISSUE THREAD

**Issue by muhghazaliakbar** [w3id/webunconfid-website#7]
<img width="1250" alt="screenshot 2018-09-13 19 44 55" src="https://user-images.githubusercontent.com/8321936/45486485-db297880-b78d-11e8-869f-dc78c6ce2cd3.png">

**Comment by mazipan** [comment]
Not all those community have logo I think

**Comment by muhghazaliakbar** [comment]
Hmm yeah, you're right 🤔

**Comment by tyohan** [comment]
Mungkin minimal link ke meetup.com, medium, atau group. Kalau ada yang mo ubah comment di sini dulu aja biar ga overlapping.

**Comment by tyohan** [comment]
Anyone mau update link ke group masing?

**Comment by mazipan** [comment]
Close #7 and move to #33 for better tracking
