### ISSUE TITLE
Remove unnecessary arrow in mobile web

### ISSUE THREAD

**Issue by mazipan** [w3id/webunconfid-website#8]
<img width="397" alt="screen shot 2018-09-13 at 18 47 51" src="https://user-images.githubusercontent.com/7221389/45486510-98fc3900-b785-11e8-8416-e4881acaea23.png">

This arrow is not good for mobile web because we already have hamburger menu.
Please add media query css to hide in mobile web.

**Comment by praditautama** [comment]
![image](https://user-images.githubusercontent.com/2928788/45528064-cfc76300-b808-11e8-91bf-bea691c1c069.png)
Is this intentional @ri7nz @tyohan ? small unstyled arrow in mobile (iPhone 5/SE).
