### ISSUE TITLE
Can we have favicon?

### ISSUE THREAD

**Issue by mazipan** [w3id/webunconfid-website#9]
Weird to access web without favicon.
Can we use WWWID logo @tyohan ?

**Comment by praditautama** [comment]
Like this, maybe? https://github.com/w3id/webunconfid-website/pull/18

**Comment by tyohan** [comment]
We're hiring a designer now to design wwwid logo. Will use favicon once we have logo ready.

**Comment by tyohan** [comment]
Kita pake favicon sementara. Nanti di-replace kalau design dah ready.
